name: CI/CD Pipeline

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - synchronize

permissions:
  contents: write

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-modules.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y npm ethereum
          npm install
          go get -d github.com/ethereum/go-ethereum@v1.12.2 \
          && go install github.com/ethereum/go-ethereum/cmd/abigen@v1.12.2 \
          && go install github.com/mattn/goveralls@v0.0.11 \
          && go install github.com/ory/go-acc@v0.2.7 \
          && go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2

      - name: Cache Node modules
        uses: actions/cache@v3
        id: cache-modules
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-modules-

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.OS }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go-mod-

  test:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Use cached Node modules
        if: steps.cache-modules.outputs.cache-hit == 'true'
        run: npm ci

      - name: Use cached Go modules
        if: needs.setup-environment.outputs.cache-hit == 'true'
        run: go mod download

      - name: Run make setup for mainnet
        run: make setup

      - name: Run gofmt
        run: gofmt

      - name: Run golangci-lint
        run: golangci-lint run -v --timeout 5m

      - name: Execute test case
        run: >
          go-acc ./... --ignore razor/accounts/mocks --ignore razor/cmd/mocks
          --ignore razor/utils/mocks --ignore pkg --ignore razor/path/mocks
          --output coverage.txt

      - name: Run benchmarks
        run: go test ./... -bench=. -run=^#

      - name: Publish Coverage to Coveralls.io
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.txt -service=github

  # build-amd:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     #... (Keep the same steps for building and uploading the AMD artifact)

  # build-arm:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     #... (Keep the same steps for building and uploading the ARM artifact)

  # publish-github-release:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build-amd
  #     - build-arm
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   steps:
  #     #... (Keep the same steps for publishing to GitHub releases)

  # push-docker-build:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   steps:
  #     #... (Keep the same steps for building and pushing the Docker image)
