# CI/CD Pipeline for Building and Releasing the Razor Application
# Phases: Setup -> Test -> Build (AMD64 & ARM64) -> Release -> Docker Build

name: CI/CD Pipeline

on: [push]

permissions:
  contents: read

env:
  AMD_ARTIFACT_NAME: razor_go.linux-amd64.tar.gz
  ARM_ARTIFACT_NAME: razor_go.linux-arm64.tar.gz

# Initial setup: Checkout, Node and Go setup, and dependencies installation.
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      amd_artifact: ${{ steps.define.outputs.amd_artifact }}
      arm_artifact: ${{ steps.define.outputs.arm_artifact }}
    steps:
      - name: Define Artifact Names
        id: define
        run: |
          echo "::set-output name=amd_artifact::$AMD_ARTIFACT_NAME"
          echo "::set-output name=arm_artifact::$ARM_ARTIFACT_NAME"

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"
        
      - name: Add Go binaries to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install Project Dependencies
        run: |
          # Ethereum setup
          sudo add-apt-repository -y ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y ethereum

          # Node.js and Go dependencies
          if [ ! -d "node_modules" ]; then
            npm install
          fi
          go get -d github.com/ethereum/go-ethereum@v1.10.8
          go install github.com/ethereum/go-ethereum/cmd/abigen@v1.10.8
          go install github.com/mattn/goveralls@v0.0.11
          go install github.com/ory/go-acc@v0.2.7
          # go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  # Test phase: code setup, linting, unit tests, and benchmarking
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Restore Node modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Restore Go modules from cache
        uses: actions/cache@v2
        with:
          path: ~/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Print PATH and Check abigen
        run: |
          echo "PATH: $PATH"
          if [ -f "$HOME/go/bin/abigen" ]; then
            echo "abigen is present in $HOME/go/bin"
          else
            echo "abigen NOT found in $HOME/go/bin"
          fi
      
      - name: Add go binaries to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH
      
      - name: Set GOROOT
        run: echo "GOROOT=$(go env GOROOT)" >> $GITHUB_ENV

      - name: Project Setup
        run: make setup

      - name: Check Code Formatting with gofmt
        run: gofmt -l .

      # - name: Lint Code with golangci-lint
      #   run: golangci-lint run -v --timeout 5m

      - name: "Lint Code with golangci-lint"
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2

      - name: Execute Test Cases
        run: |
          go-acc ./... --ignore razor/accounts/mocks --ignore razor/cmd/mocks
          --ignore razor/utils/mocks --ignore pkg --ignore razor/path/mocks
          --output coverage.txt

      - name: Run Benchmarks
        run: go test ./... -bench=. -run=^#

      - name: Publish Coverage Report
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.txt -service=github


# Build phase: create AMD64 and ARM64 artifacts
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Create ${{ matrix.platform }} Artifact
        run: |
          ARTIFACT_NAME=${{ matrix.platform == 'amd64' && needs.setup.outputs.amd_artifact || needs.setup.outputs.arm_artifact }}
          npm i
          npm run build-noargs
          cd build/bin
          tar -czvf $ARTIFACT_NAME razor
          mv $ARTIFACT_NAME ../../
      - name: Upload ${{ matrix.platform }} Artifact
        uses: actions/upload-artifact@v2
        with:
          name: $ARTIFACT_NAME
          path: $ARTIFACT_NAME

  # Release phase: download artifacts and release on GitHub
  publish-github-release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: List Downloaded Files
        run: ls -R
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            ${{ needs.setup.outputs.amd_artifact }}
            ${{ needs.setup.outputs.arm_artifact }}

  # Docker phase: build and push Docker images
  push-docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract Release Tag
        id: extract_tag
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: coolsamosa/node-test:${{ steps.extract_tag.outputs.tag_name }}


